
package com.autotownmayor.server.quickbooks.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QBWebConnectorSvcSoap", targetNamespace = "http://developer.intuit.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QBWebConnectorSvcSoap {


    /**
     * 
     * @param strVersion
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://developer.intuit.com/serverVersion")
    @WebResult(name = "serverVersionResult", targetNamespace = "http://developer.intuit.com/")
    @RequestWrapper(localName = "serverVersion", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.ServerVersion")
    @ResponseWrapper(localName = "serverVersionResponse", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.ServerVersionResponse")
    public String serverVersion(
        @WebParam(name = "strVersion", targetNamespace = "http://developer.intuit.com/")
        String strVersion);

    /**
     * 
     * @param strVersion
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://developer.intuit.com/clientVersion")
    @WebResult(name = "clientVersionResult", targetNamespace = "http://developer.intuit.com/")
    @RequestWrapper(localName = "clientVersion", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.ClientVersion")
    @ResponseWrapper(localName = "clientVersionResponse", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.ClientVersionResponse")
    public String clientVersion(
        @WebParam(name = "strVersion", targetNamespace = "http://developer.intuit.com/")
        String strVersion);

    /**
     * 
     * @param strUserName
     * @param strPassword
     * @return
     *     returns com.autotownmayor.server.quickbooks.ws.ArrayOfString
     */
    @WebMethod(action = "http://developer.intuit.com/authenticate")
    @WebResult(name = "authenticateResult", targetNamespace = "http://developer.intuit.com/")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.AuthenticateResponse")
    public ArrayOfString authenticate(
        @WebParam(name = "strUserName", targetNamespace = "http://developer.intuit.com/")
        String strUserName,
        @WebParam(name = "strPassword", targetNamespace = "http://developer.intuit.com/")
        String strPassword);

    /**
     * 
     * @param qbXMLMinorVers
     * @param qbXMLCountry
     * @param ticket
     * @param qbXMLMajorVers
     * @param strCompanyFileName
     * @param strHCPResponse
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://developer.intuit.com/sendRequestXML")
    @WebResult(name = "sendRequestXMLResult", targetNamespace = "http://developer.intuit.com/")
    @RequestWrapper(localName = "sendRequestXML", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.SendRequestXML")
    @ResponseWrapper(localName = "sendRequestXMLResponse", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.SendRequestXMLResponse")
    public String sendRequestXML(
        @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com/")
        String ticket,
        @WebParam(name = "strHCPResponse", targetNamespace = "http://developer.intuit.com/")
        String strHCPResponse,
        @WebParam(name = "strCompanyFileName", targetNamespace = "http://developer.intuit.com/")
        String strCompanyFileName,
        @WebParam(name = "qbXMLCountry", targetNamespace = "http://developer.intuit.com/")
        String qbXMLCountry,
        @WebParam(name = "qbXMLMajorVers", targetNamespace = "http://developer.intuit.com/")
        int qbXMLMajorVers,
        @WebParam(name = "qbXMLMinorVers", targetNamespace = "http://developer.intuit.com/")
        int qbXMLMinorVers);

    /**
     * 
     * @param hresult
     * @param ticket
     * @param response
     * @param message
     * @return
     *     returns int
     */
    @WebMethod(action = "http://developer.intuit.com/receiveResponseXML")
    @WebResult(name = "receiveResponseXMLResult", targetNamespace = "http://developer.intuit.com/")
    @RequestWrapper(localName = "receiveResponseXML", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.ReceiveResponseXML")
    @ResponseWrapper(localName = "receiveResponseXMLResponse", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.ReceiveResponseXMLResponse")
    public int receiveResponseXML(
        @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com/")
        String ticket,
        @WebParam(name = "response", targetNamespace = "http://developer.intuit.com/")
        String response,
        @WebParam(name = "hresult", targetNamespace = "http://developer.intuit.com/")
        String hresult,
        @WebParam(name = "message", targetNamespace = "http://developer.intuit.com/")
        String message);

    /**
     * 
     * @param hresult
     * @param ticket
     * @param message
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://developer.intuit.com/connectionError")
    @WebResult(name = "connectionErrorResult", targetNamespace = "http://developer.intuit.com/")
    @RequestWrapper(localName = "connectionError", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.ConnectionError")
    @ResponseWrapper(localName = "connectionErrorResponse", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.ConnectionErrorResponse")
    public String connectionError(
        @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com/")
        String ticket,
        @WebParam(name = "hresult", targetNamespace = "http://developer.intuit.com/")
        String hresult,
        @WebParam(name = "message", targetNamespace = "http://developer.intuit.com/")
        String message);

    /**
     * 
     * @param ticket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://developer.intuit.com/getLastError")
    @WebResult(name = "getLastErrorResult", targetNamespace = "http://developer.intuit.com/")
    @RequestWrapper(localName = "getLastError", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.GetLastError")
    @ResponseWrapper(localName = "getLastErrorResponse", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.GetLastErrorResponse")
    public String getLastError(
        @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com/")
        String ticket);

    /**
     * 
     * @param ticket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://developer.intuit.com/closeConnection")
    @WebResult(name = "closeConnectionResult", targetNamespace = "http://developer.intuit.com/")
    @RequestWrapper(localName = "closeConnection", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.CloseConnection")
    @ResponseWrapper(localName = "closeConnectionResponse", targetNamespace = "http://developer.intuit.com/", className = "com.autotownmayor.server.quickbooks.ws.CloseConnectionResponse")
    public String closeConnection(
        @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com/")
        String ticket);

}
