
package com.autotownmayor.server.quickbooks.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QBWebConnectorSvc", targetNamespace = "http://developer.intuit.com/", wsdlLocation = "file:/D:/CS_Projects/AutoTownMayor/web-app/server/src/main/java/QBWebConnectorSvc.wsdl")
public class QBWebConnectorSvc
    extends Service
{

    private final static URL QBWEBCONNECTORSVC_WSDL_LOCATION;
    private final static WebServiceException QBWEBCONNECTORSVC_EXCEPTION;
    private final static QName QBWEBCONNECTORSVC_QNAME = new QName("http://developer.intuit.com/", "QBWebConnectorSvc");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/CS_Projects/AutoTownMayor/web-app/server/src/main/java/QBWebConnectorSvc.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QBWEBCONNECTORSVC_WSDL_LOCATION = url;
        QBWEBCONNECTORSVC_EXCEPTION = e;
    }

    public QBWebConnectorSvc() {
        super(__getWsdlLocation(), QBWEBCONNECTORSVC_QNAME);
    }

    public QBWebConnectorSvc(WebServiceFeature... features) {
        super(__getWsdlLocation(), QBWEBCONNECTORSVC_QNAME, features);
    }

    public QBWebConnectorSvc(URL wsdlLocation) {
        super(wsdlLocation, QBWEBCONNECTORSVC_QNAME);
    }

    public QBWebConnectorSvc(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QBWEBCONNECTORSVC_QNAME, features);
    }

    public QBWebConnectorSvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QBWebConnectorSvc(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QBWebConnectorSvcSoap
     */
    @WebEndpoint(name = "QBWebConnectorSvcSoap")
    public QBWebConnectorSvcSoap getQBWebConnectorSvcSoap() {
        return super.getPort(new QName("http://developer.intuit.com/", "QBWebConnectorSvcSoap"), QBWebConnectorSvcSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QBWebConnectorSvcSoap
     */
    @WebEndpoint(name = "QBWebConnectorSvcSoap")
    public QBWebConnectorSvcSoap getQBWebConnectorSvcSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://developer.intuit.com/", "QBWebConnectorSvcSoap"), QBWebConnectorSvcSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QBWEBCONNECTORSVC_EXCEPTION!= null) {
            throw QBWEBCONNECTORSVC_EXCEPTION;
        }
        return QBWEBCONNECTORSVC_WSDL_LOCATION;
    }

}
